spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    name: rneretin_otus
    username: otus
    password: Y&2BINv@89Q8
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql