spring:
  datasource:
    url: jdbc:mysql://localhost:3307?allowPublicKeyRetrieval=true&useSSL=false
    name: rneretin_otus
    username: otus
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql